<a href="https://colab.research.google.com/github/ravi-yadav-98/Learning-Pytorch-/blob/main/L1_Pytorch_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install torch


### **Learning Pytorch: Chapter:01**



#### Tensors in PyTorch : Tensors are just higher-dimensional matrices

In [1]:
import torch

In [3]:
# creating a scalar, and three tensors (vector, matrix, tensor)
scalar = torch.tensor(3.14159)
vector = torch.tensor([1, 2, 3])
matrix = torch.ones((2, 3), dtype=torch.float)
tensor = torch.randn((2, 3, 4), dtype=torch.float)

print(scalar)
print(vector)
print(matrix)
print(tensor)
print("Size of tensor:", tensor.size())

tensor(3.1416)
tensor([1, 2, 3])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[[-0.6505,  0.4444, -1.5450,  0.3309],
         [-0.5431, -0.5348,  2.2983,  0.4345],
         [ 0.5947, -1.5732,  0.8248, -1.6411]],

        [[ 2.3326,  1.0350,  1.3627, -0.4064],
         [ 2.4085,  0.2063, -2.4676,  0.1924],
         [-0.8131, -0.1894,  0.4631, -0.4069]]])
Size of tensor: torch.Size([2, 3, 4])


In [4]:
# creating a scalar and printing it's shape
scalar = torch.tensor(3.14159)
print(scalar.size(), scalar.shape)

torch.Size([]) torch.Size([])


##### Reshape Tensors

In [11]:
mat = torch.ones((2, 3))
print(mat.size())

#reshape
reshaped_mat = mat.view(1, 6)
print(reshaped_mat.size())

# mat.view does not create new memory, it is just a different view of the same data
mat[0, 0] = 99
print(mat)
print(reshaped_mat)

torch.Size([2, 3])
torch.Size([1, 6])
tensor([[99.,  1.,  1.],
        [ 1.,  1.,  1.]])
tensor([[99.,  1.,  1.,  1.,  1.,  1.]])


In [12]:
#### Create clones of tensors to have independent memory
matrix = torch.ones((2, 3), dtype=torch.float)
# Lets follow PyTorch's suggestion and use "clone" method
another_matrix = matrix.view(1, 6).clone().detach()
# Again, if we change one of its elements...
another_matrix[0, 1] = 4.
# The original tensor (matrix) is left untouched!
print(matrix)
print(another_matrix)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 4., 1., 1., 1., 1.]])


#### Numpy to Tensor

In [13]:
import numpy as np
import torch

dummy_array = np.array([1, 2, 3])
dummy_tensor = torch.as_tensor(dummy_array)
# Modifies the numpy array
dummy_array[1] = 0
# Tensor gets modified too...
print(dummy_tensor)

tensor([1, 0, 3])


In [14]:
dummy_array = np.array([1, 2, 3])
dummy_tensor = torch.as_tensor(dummy_array)
# Modifies the numpy array
dummy_array[1] = 0
# Using numpy function to convert PyTorch tensor to Numpy array
print(dummy_tensor.numpy())

[1 0 3]


#### GPU Tensors

In [15]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print('Using device:', device)

Using device: cpu


In [ ]:
gpu_tensor = torch.as_tensor(x_train).to(device)
print(gpu_tensor[0])