### Linear Regression in Pytorch from Scratch 

In [1]:
import torch
import torch.nn as nn

In [2]:
x = torch.tensor([1., 2., 3., 4., 5.])
y = torch.tensor([3., 5., 7., 9., 11.])

In [3]:
# y = b + w * x

lr = 0.01
epochs = 1000

m = torch.randn(1, requires_grad=True)
c = torch.randn(1, requires_grad=True)

for _ in range(epochs):
    y_hat = m * x + c
    loss = ((y_hat - y) ** 2).mean()
    loss.backward()

    with torch.no_grad():
        m -= lr * m.grad
        c -= lr * c.grad

        m.grad.zero_()
        c.grad.zero_()

print(m.item(), c.item())

2.00070858001709 0.997442901134491


In [9]:
p = nn.Parameter(torch.randn(1))
print(p.requires_grad)

True


#### Using nn.Module (Neural Network)

In [4]:
class LinearRegression(nn.Module):
    def __init__(self):
        super().__init__()
        self.m = nn.Parameter(torch.randn(1))
        self.c = nn.Parameter(torch.randn(1))

    def forward(self, x):
        return self.m * x + self.c

model = LinearRegression()
print(model.state_dict())

loss_fn = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

epochs = 1000

for _ in range(epochs):
    model.train()
    y_hat = model(x)
    loss = loss_fn(y_hat, y)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

print(model.m.item(), model.c.item())


OrderedDict({'m': tensor([1.1934]), 'c': tensor([-2.1704])})
2.025639295578003 0.907433807849884


In [5]:
model.state_dict()

OrderedDict([('m', tensor([2.0256])), ('c', tensor([0.9074]))])

In [6]:
# x = torch.tensor([1., 2., 3., 4., 5.])
x = torch.tensor([[1.], [2.], [3.], [4.], [5.]])
x.size()

torch.Size([5, 1])

### 2-Layer Neural Network (nn.Module)

In [10]:
class SimpleNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(1, 16)   # input → hidden
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(16, 1)   # hidden → output

    def forward(self, x):
        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        return x


x = torch.tensor([[1.], [2.], [3.], [4.], [5.]])
y = torch.tensor([[3.], [5.], [7.], [9.], [11.]])
model = SimpleNN()

loss_fn = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

epochs = 20

for epoch in range(epochs):
    y_hat = model(x)
    loss = loss_fn(y_hat, y)
    print("Epoch:{}, loss {}".format(epoch,loss))

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

print(y_hat.detach())


Epoch:0, loss 48.603233337402344
Epoch:1, loss 16.96790885925293
Epoch:2, loss 2.554988384246826
Epoch:3, loss 0.03677799925208092
Epoch:4, loss 0.004336358048021793
Epoch:5, loss 0.00416181143373251
Epoch:6, loss 0.004026600159704685
Epoch:7, loss 0.003896582406014204
Epoch:8, loss 0.003771331626921892
Epoch:9, loss 0.003650737926363945
Epoch:10, loss 0.0035346553195267916
Epoch:11, loss 0.003422859590500593
Epoch:12, loss 0.003315241541713476
Epoch:13, loss 0.003211598377674818
Epoch:14, loss 0.0031118025071918964
Epoch:15, loss 0.003015729133039713
Epoch:16, loss 0.0029232113156467676
Epoch:17, loss 0.0028341228608042
Epoch:18, loss 0.0027483224403113127
Epoch:19, loss 0.0026657029520720243
tensor([[ 3.1096],
        [ 5.0238],
        [ 6.9935],
        [ 8.9867],
        [10.9768]])


In [12]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.9427],
         [-0.1918],
         [-0.1485],
         [-0.0520],
         [-0.7596],
         [ 0.9370],
         [ 0.6850],
         [ 0.1001],
         [-0.8762],
         [-0.2315],
         [-0.7197],
         [ 0.1325],
         [-0.6462],
         [ 0.4386],
         [-0.7587],
         [ 0.3822]], requires_grad=True),
 Parameter containing:
 tensor([ 1.0436, -0.5199,  0.3907,  0.8403, -0.6376, -0.0971, -0.8185, -0.4794,
         -0.7921, -0.7319,  0.3851,  0.2373,  0.6100, -0.2258, -0.9137, -0.3343],
        requires_grad=True),
 Parameter containing:
 tensor([[ 0.9436,  0.0429,  0.2490,  0.2377, -0.0019,  0.6529,  0.3146, -0.1401,
          -0.1750,  0.1822, -0.2422,  0.2098,  0.1282,  0.3317, -0.1165,  0.3032]],
        requires_grad=True),
 Parameter containing:
 tensor([0.2750], requires_grad=True)]

In [15]:
import torch.nn as nn

linear = nn.Linear(2, 2)
type(linear.state_dict())
isinstance(linear.state_dict(), dict)

True